name: Metrics
on:
  # Atualiza o calendário todos os dias à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar o workflow manualmente na aba "Actions"
  workflow_dispatch:
  # (Opcional) Atualiza sempre que você fizer um push neste repositório
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "" # Deixa a imagem focada apenas no calendário
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
